# Uncomment this line to define a global platform for your project
#platform :ios, '8.0'
use_frameworks!

target 'Openhome' do
pod 'GoogleMaps'
pod "NMPopUpViewSwift"
pod 'Firebase', '>= 2.4.2'
end

target 'OpenhomeTests' do

end

target 'OpenhomeUITests' do

end
